POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV2YSIsImlkIjoiNjVjNGYwMjE2ZWQ3ZjFhMjVlMzY2YjhkIiwiaWF0IjoxNzA3NDA1MzYyLCJleHAiOjE3MDc0MDg5NjJ9.bCDv_22csNv5lCFfviBwgueTrQGjzUOO-W9u1XfJ6Yw

{
    "title": "eva post",
    "author": "a",
    "url": "a",
    "likes": 0
}